<!-- Slider -->
<div id="main-slider">
        <div id="slider-holder">
            
        </div>
<!-- Content -->
<div id="content">
        <!-- Case -->
        <div class="case">
                <h3>Login</h3>
                <!-- Row -->
                <div class="row">
                    <div id="content">
                        <?php
                            echo $this->form;
                        ?>
                    </div>
                    <div class="cl">&nbsp;</div>
                </div>
                <!-- End Row -->
        </div>
        <!-- End Case -->
</div>
<!-- End Content -->
