<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
	<title>ExBidience</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="css/images/favicon.ico" />
	<link rel="stylesheet" href="css/style.css" type="text/css" media="all" />
	<!--[if IE 6]>
		<link rel="stylesheet" href="css/ie6.css" type="text/css" media="media" />
		<script src="js/png-fix.js" type="text/javascript" charset="utf-8"></script>
	<![endif]-->
	<script src="js/jquery-1.6.2.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/jquery.jcarousel.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/jquery-func.js" type="text/javascript" charset="utf-8"></script>	
</head>
<body>
	<!-- Wrapper -->
	<div id="wrapper">
		<!-- Header -->
		<div id="top">
			<!-- Shell -->
			<div class="shell">
				<div class="top-nav">
					<ul>
					    <li class="first nobg"><p title="Default welcome msg">Welcome to Exbidience</p></li>
					    <li><a href="login" title="Login">Login</a></li>
					    <li><a href="#" title="My Account">My Account</a></li>
					    <li class="nobg"><a href="#" class="bag" title="My Bids">My Bids</a></li>
					</ul>
				</div>
				<div id="search">
					<form action="" method="post">
						<input type="text" class="field" value="Quick search..." title="Quick search..." />
					</form>
				</div>
				<div class="cl">&nbsp;</div>
			</div>
			<!-- End Shell -->
		</div>
		<!-- End Top -->
		<!-- Main -->
		<div id="main">
			<!-- Shell -->
			<div class="shell">
                            <!-- Header -->
                            <div id="header">
                                    <h1 id="logo"><a href="/" class="notext" title="Exbidience">Exbidience</a></h1>
                                    <div id="navigation">
                                            <ul>
                                                <li><a href="#" title="Adventure"><span>Adventure</span></a></li>
                                                <li><a href="#" title="Hotels"><span>Hotels</span></a></li>
                                                <li><a href="#" title="Cruises"><span>Cruises</span></a></li>
                                            </ul>
                                    </div>
                                    <div class="cl">&nbsp;</div>
                            </div>
                            <!-- End Header -->
                            <?php echo $this->layout()->content ?>
			</div>
			<!-- End Shell -->
		</div>
		<!-- End Main -->
		<div id="footer-push" class="cl">&nbsp;</div>
	</div>
	<!-- End Wrapper -->
	<!-- Footer -->
	<div id="footer">
		<!-- Shell -->
		<div class="shell">
			<!-- Cols -->
			<div class="cols">
				<ul>
				    <li class="col">
				    	<h4>about wooden toy</h4>
				    	<p>Quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. <a href="#" title="Duis autem">Duis autem</a> vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu</p>
				    	<a href="#" class="more-link" title="Read More">Read More >></a>
				    </li>
				    <li class="col social">
				    	<h4>get social</h4>
				    	<ul>
				    	    <li><a href="#" class="fb-link" title="Facebook">facebook</a></li>
				    	    <li><a href="#" class="twitter-link" title="Twitter">twitter</a></li>
				    	    <li><a href="#" class="behance-link" title="Behance">behance</a></li>
				    	    <li><a href="#" class="blogger-link" title="Blogger">blogger</a></li>
				    	    <li><a href="#" class="digg-link" title="Digg">digg</a></li>
				    	</ul>
				    </li>
				    <li class="col partners">
				    	<h4>partners</h4>
				    	<ul>
				    	    <li><a href="#" title="Lorem ipsum dolor">Lorem ipsum dolor</a></li>
				    	    <li><a href="#" title="Cras eu lorem id mauris">Cras eu lorem id mauris</a></li>
				    	    <li><a href="#" title="Proin et velit ut libero">Proin et velit ut libero</a></li>
				    	    <li><a href="#" title="Velit esse molestie consequat">Velit esse molestie consequat</a></li>
				    	    <li><a href="#" title="Vel illum dolore eu">Vel illum dolore eu</a></li>
				    	</ul>
				    </li>
				    <li class="col contact">
				    	<h4>newsletter</h4>
				    	<p>Etiam consectetur dui dignissim nulla</p>
				    	<form action="" method="post">
				    		<div class="field-wrapper">
				    			<input type="text" class="field" value="Name" title="Name" />
				    		</div>
				    		<div class="field-wrapper">
				    			<input type="text" class="field" value="Email" title="Email" />
				    		</div>
				    		<input type="submit" value="Submit" class="submit-btn" title="Submit" />
				    		<div class="cl">&nbsp;</div>
				    	</form>
				    </li>
				</ul>
				<div class="cl">&nbsp;</div>
			</div>
			<!-- End Cols -->
			<p class="copy">&copy; Sitename.com. Design by <a href="http://css-free-templates.com/">CSS-FREE-TEMPLATES.COM</a></p>
			<a href="#" class="logo" title="Shopper Friend"><img src="css/images/footer-logo.png" alt="Shopper Friend" /></a>
			<div class="cl">&nbsp;</div>
		</div>
		<!-- End Shell -->
	</div>
	<!-- End Footer -->
</body>
</html>